import express from 'express';
import { authentication } from '../../middlewares/authentication';
import adminsRoutes from './sub-routes/adminsRoutes';
import authRoutes from './sub-routes/authRoutes';
import orderRoutes from './sub-routes/orderRoutes';
import productsRoutes from './sub-routes/productsRoutes';
import shopsRoutes from './sub-routes/shopsRoutes';
import templateRouter from './sub-routes/tempMassageRoutes';
import usersRoutes from './sub-routes/usersRoutes';
import sellerDasboard from './sub-routes/sellerRoutes';
import withdrawRoutes from './sub-routes/withdrawRoutes';
import invoiceRoutes from './sub-routes/invoiceRoutes';
import webhookRoutes from './sub-routes/webhookRoutes';
import bankRouter from './sub-routes/banksRouter';

const app = express();

app.use('/auth', authRoutes);
app.use('/users', usersRoutes);
app.use('/shops', authentication, shopsRoutes);
app.use('/products', productsRoutes);
app.use('/orders', orderRoutes);
app.use('/admins', adminsRoutes);
app.use('/template-message', authentication, templateRouter);
app.use('/seller', authentication, sellerDasboard);
app.use('/withdraw', authentication, withdrawRoutes);
app.use('/invoice', invoiceRoutes);
app.use('/webhook', webhookRoutes);
app.use('/bank', authentication, bankRouter);
export const API_V1 = app;
