export const categories = [
  { id: 'z-cat-others-1', label: 'Others', value: 'Others' },
  {
    id: 'z-cat-children-2',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-1',
  },
  {
    id: 'z-cat-children-3',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-27',
  },
  {
    id: 'z-cat-children-4',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-53',
  },
  {
    id: 'z-cat-children-5',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-100',
  },
  {
    id: 'z-cat-children-6',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-200',
  },
  {
    id: 'z-cat-children-7',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-300',
  },
  {
    id: 'z-cat-children-8',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-400',
  },
  {
    id: 'z-cat-children-9',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-500',
  },
  {
    id: 'z-cat-children-10',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-600',
  },

  {
    id: 'z-cat-sub-children-1',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-2',
  },
  {
    id: 'z-cat-sub-children-2',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-3',
  },
  {
    id: 'z-cat-sub-children-3',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-4',
  },
  {
    id: 'z-cat-sub-children-4',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-5',
  },

  {
    id: 'z-cat-sub-children-6',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-28',
  },
  {
    id: 'z-cat-sub-children-7',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-29',
  },
  {
    id: 'z-cat-sub-children-8',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-30',
  },
  {
    id: 'z-cat-sub-children-9',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-31',
  },
  {
    id: 'z-cat-sub-children-10',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-32',
  },
  {
    id: 'z-cat-sub-children-11',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-33',
  },
  {
    id: 'z-cat-sub-children-12',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-34',
  },

  {
    id: 'z-cat-sub-children-13',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-54',
  },
  {
    id: 'z-cat-sub-children-14',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-55',
  },
  {
    id: 'z-cat-sub-children-15',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-56',
  },
  {
    id: 'z-cat-sub-children-16',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-57',
  },
  {
    id: 'z-cat-sub-children-17',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-58',
  },
  {
    id: 'z-cat-sub-children-18',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-59',
  },

  {
    id: 'z-cat-sub-children-19',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-101',
  },
  {
    id: 'z-cat-sub-children-20',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-102',
  },
  {
    id: 'z-cat-sub-children-21',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-103',
  },
  {
    id: 'z-cat-sub-children-22',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-104',
  },

  {
    id: 'z-cat-sub-children-23',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-201',
  },
  {
    id: 'z-cat-sub-children-24',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-202',
  },
  {
    id: 'z-cat-sub-children-25',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-203',
  },
  {
    id: 'z-cat-sub-children-26',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-204',
  },

  {
    id: 'z-cat-sub-children-27',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-301',
  },
  {
    id: 'z-cat-sub-children-28',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-302',
  },
  {
    id: 'z-cat-sub-children-29',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-303',
  },
  {
    id: 'z-cat-sub-children-30',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-304',
  },

  {
    id: 'z-cat-sub-children-31',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-401',
  },
  {
    id: 'z-cat-sub-children-32',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-402',
  },
  {
    id: 'z-cat-sub-children-33',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-403',
  },
  {
    id: 'z-cat-sub-children-34',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-404',
  },

  {
    id: 'z-cat-sub-children-35',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-501',
  },
  {
    id: 'z-cat-sub-children-36',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-502',
  },
  {
    id: 'z-cat-sub-children-37',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-503',
  },
  {
    id: 'z-cat-sub-children-38',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-504',
  },

  {
    id: 'z-cat-sub-children-39',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-601',
  },
  {
    id: 'z-cat-sub-children-40',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-602',
  },
  {
    id: 'z-cat-sub-children-41',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-603',
  },
  {
    id: 'z-cat-sub-children-42',
    label: 'Others',
    value: 'Others',
    parent_id: 'cat-604',
  },
  {
    id: 'cat-1',
    label: 'Man Fashion',
    value: 'man-fashion',
  },
  {
    id: 'cat-2',
    parent_id: 'cat-1',
    label: 'Man Outer',
    value: 'man-outer',
  },
  {
    id: 'cat-3',
    parent_id: 'cat-1',
    label: 'Man Accesories',
    value: 'man-accesories',
  },
  {
    id: 'cat-4',
    parent_id: 'cat-1',
    label: 'Man Pants',
    value: 'man-pants',
  },
  {
    id: 'cat-5',
    parent_id: 'cat-1',
    label: 'Man Shoes',
    value: 'man-shoes',
  },
  {
    id: 'cat-7',
    parent_id: 'cat-2',
    label: 'Bomber Jacket',
    value: 'bomber-jaket',
  },
  {
    id: 'cat-8',
    parent_id: 'cat-2',
    label: 'Parka Jaket',
    value: 'parka-jacket',
  },
  {
    id: 'cat-9',
    parent_id: 'cat-2',
    label: 'Denim Jacket',
    value: 'denim-jacket',
  },
  {
    id: 'cat-10',
    parent_id: 'cat-2',
    label: 'Windbreaker Jacket',
    value: 'winbreaker-jacket',
  },
  {
    id: 'cat-11',
    parent_id: 'cat-2',
    label: 'Puffer Jacket',
    value: 'puffer-jacket',
  },
  {
    id: 'cat-12',
    parent_id: 'cat-3',
    label: 'Man Watches',
    value: 'man-watches',
  },
  {
    id: 'cat-13',
    parent_id: 'cat-3',
    label: 'Man Glasses',
    value: 'man-glasses',
  },
  {
    id: 'cat-14',
    parent_id: 'cat-3',
    label: 'Man Hats',
    value: 'man-hats',
  },
  {
    id: 'cat-15',
    parent_id: 'cat-3',
    label: 'Man Bags',
    value: 'man-bags',
  },
  {
    id: 'cat-16',
    parent_id: 'cat-3',
    label: 'Man Belts',
    value: 'man-belts',
  },
  {
    id: 'cat-17',
    parent_id: 'cat-4',
    label: 'Man Jeans',
    value: 'man-jeans',
  },
  {
    id: 'cat-18',
    parent_id: 'cat-4',
    label: 'Man Chinos',
    value: 'man-chinos',
  },
  {
    id: 'cat-19',
    parent_id: 'cat-4',
    label: 'Man Cargos',
    value: 'man-cargo',
  },
  {
    id: 'cat-20',
    parent_id: 'cat-4',
    label: 'Man Joggers',
    value: 'man-jogger',
  },
  {
    id: 'cat-21',
    parent_id: 'cat-4',
    label: 'Man Shorts',
    value: 'man-shorts',
  },
  {
    id: 'cat-22',
    parent_id: 'cat-5',
    label: 'Man Formals',
    value: 'man-formals',
  },
  {
    id: 'cat-23',
    parent_id: 'cat-5',
    label: 'Man Oxfords',
    value: 'man-oxfords',
  },
  {
    id: 'cat-24',
    parent_id: 'cat-5',
    label: 'Man Derbys',
    value: 'man-derbys',
  },
  {
    id: 'cat-25',
    parent_id: 'cat-5',
    label: 'Man Loafers',
    value: 'man-loafers',
  },
  {
    id: 'cat-26',
    parent_id: 'cat-5',
    label: 'Man Sneakers',
    value: 'man-sneakers',
  },
  {
    id: 'cat-27',
    label: 'Electronics',
    value: 'electronics',
  },
  {
    id: 'cat-28',
    parent_id: 'cat-27',
    label: 'Mobile Phones',
    value: 'mobile-phones',
  },
  {
    id: 'cat-29',
    parent_id: 'cat-27',
    label: 'Laptops',
    value: 'laptops',
  },
  {
    id: 'cat-30',
    parent_id: 'cat-27',
    label: 'Headphones',
    value: 'headphones',
  },
  {
    id: 'cat-31',
    parent_id: 'cat-27',
    label: 'Smart Watches',
    value: 'smart-watches',
  },
  {
    id: 'cat-32',
    parent_id: 'cat-27',
    label: 'Tablets',
    value: 'tablets',
  },
  {
    id: 'cat-33',
    parent_id: 'cat-27',
    label: 'Cameras',
    value: 'cameras',
  },
  {
    id: 'cat-34',
    parent_id: 'cat-27',
    label: 'Home Appliances',
    value: 'home-appliances',
  },
  {
    id: 'cat-35',
    parent_id: 'cat-28',
    label: 'Smartphones',
    value: 'smartphones',
  },
  {
    id: 'cat-36',
    parent_id: 'cat-28',
    label: 'Feature Phones',
    value: 'feature-phones',
  },
  {
    id: 'cat-37',
    parent_id: 'cat-29',
    label: 'Gaming Laptops',
    value: 'gaming-laptops',
  },
  {
    id: 'cat-38',
    parent_id: 'cat-29',
    label: 'Ultrabooks',
    value: 'ultrabooks',
  },
  {
    id: 'cat-39',
    parent_id: 'cat-29',
    label: 'Business Laptops',
    value: 'business-laptops',
  },
  {
    id: 'cat-40',
    parent_id: 'cat-30',
    label: 'Over-Ear Headphones',
    value: 'over-ear-headphones',
  },
  {
    id: 'cat-41',
    parent_id: 'cat-30',
    label: 'In-Ear Headphones',
    value: 'in-ear-headphones',
  },
  {
    id: 'cat-42',
    parent_id: 'cat-30',
    label: 'Noise Cancelling Headphones',
    value: 'noise-cancelling-headphones',
  },
  {
    id: 'cat-43',
    parent_id: 'cat-31',
    label: 'Fitness Watches',
    value: 'fitness-watches',
  },
  {
    id: 'cat-44',
    parent_id: 'cat-31',
    label: 'Luxury Watches',
    value: 'luxury-watches',
  },
  {
    id: 'cat-45',
    parent_id: 'cat-31',
    label: 'Smart Bands',
    value: 'smart-bands',
  },
  {
    id: 'cat-46',
    parent_id: 'cat-32',
    label: 'Android Tablets',
    value: 'android-tablets',
  },
  {
    id: 'cat-47',
    parent_id: 'cat-32',
    label: 'iPads',
    value: 'ipads',
  },
  {
    id: 'cat-48',
    parent_id: 'cat-33',
    label: 'DSLR Cameras',
    value: 'dslr-cameras',
  },
  {
    id: 'cat-49',
    parent_id: 'cat-33',
    label: 'Mirrorless Cameras',
    value: 'mirrorless-cameras',
  },
  {
    id: 'cat-50',
    parent_id: 'cat-33',
    label: 'Action Cameras',
    value: 'action-cameras',
  },
  {
    id: 'cat-51',
    parent_id: 'cat-34',
    label: 'Air Conditioners',
    value: 'air-conditioners',
  },
  {
    id: 'cat-52',
    parent_id: 'cat-34',
    label: 'Refrigerators',
    value: 'refrigerators',
  },
  {
    id: 'cat-53',
    label: 'Kitchen',
    value: 'kitchen',
  },
  {
    id: 'cat-54',
    parent_id: 'cat-53',
    label: 'Cookware',
    value: 'cookware',
  },
  {
    id: 'cat-55',
    parent_id: 'cat-53',
    label: 'Kitchen Appliances',
    value: 'kitchen-appliances',
  },
  {
    id: 'cat-56',
    parent_id: 'cat-53',
    label: 'Dining',
    value: 'dining',
  },
  {
    id: 'cat-57',
    parent_id: 'cat-53',
    label: 'Storage',
    value: 'storage',
  },
  {
    id: 'cat-58',
    parent_id: 'cat-53',
    label: 'Baking',
    value: 'baking',
  },
  {
    id: 'cat-59',
    parent_id: 'cat-54',
    label: 'Cookware Sets',
    value: 'cookware-sets',
  },
  {
    id: 'cat-60',
    parent_id: 'cat-54',
    label: 'Frying Pans',
    value: 'frying-pans',
  },
  {
    id: 'cat-61',
    parent_id: 'cat-54',
    label: 'Sauce Pans',
    value: 'sauce-pans',
  },
  {
    id: 'cat-62',
    parent_id: 'cat-55',
    label: 'Blenders',
    value: 'blenders',
  },
  {
    id: 'cat-63',
    parent_id: 'cat-55',
    label: 'Microwaves',
    value: 'microwaves',
  },
  {
    id: 'cat-64',
    parent_id: 'cat-55',
    label: 'Food Processors',
    value: 'food-processors',
  },
  {
    id: 'cat-65',
    parent_id: 'cat-55',
    label: 'Coffee Machines',
    value: 'coffee-machines',
  },
  {
    id: 'cat-66',
    parent_id: 'cat-56',
    label: 'Dinnerware',
    value: 'dinnerware',
  },
  {
    id: 'cat-67',
    parent_id: 'cat-56',
    label: 'Flatware',
    value: 'flatware',
  },
  {
    id: 'cat-68',
    parent_id: 'cat-56',
    label: 'Glassware',
    value: 'glassware',
  },
  {
    id: 'cat-69',
    parent_id: 'cat-57',
    label: 'Food Storage Containers',
    value: 'food-storage-containers',
  },
  {
    id: 'cat-70',
    parent_id: 'cat-57',
    label: 'Spice Racks',
    value: 'spice-racks',
  },
  {
    id: 'cat-71',
    parent_id: 'cat-58',
    label: 'Baking Pans',
    value: 'baking-pans',
  },
  {
    id: 'cat-72',
    parent_id: 'cat-58',
    label: 'Mixing Bowls',
    value: 'mixing-bowls',
  },
  {
    id: 'cat-73',
    parent_id: 'cat-58',
    label: 'Cake Pans',
    value: 'cake-pans',
  },
  {
    id: 'cat-74',
    parent_id: 'cat-58',
    label: 'Rolling Pins',
    value: 'rolling-pins',
  },
  {
    id: 'cat-75',
    parent_id: 'cat-58',
    label: 'Cookie Cutters',
    value: 'cookie-cutters',
  },
  {
    id: 'cat-100',
    label: 'Woman Fashion',
    value: 'woman-fashion',
  },
  {
    id: 'cat-101',
    parent_id: 'cat-100',
    label: 'Clothing',
    value: 'clothing',
  },
  {
    id: 'cat-102',
    parent_id: 'cat-100',
    label: 'Footwear',
    value: 'footwear',
  },
  {
    id: 'cat-103',
    parent_id: 'cat-100',
    label: 'Accessories',
    value: 'accessories',
  },
  {
    id: 'cat-104',
    parent_id: 'cat-100',
    label: 'Bags',
    value: 'bags',
  },
  {
    id: 'cat-105',
    parent_id: 'cat-101',
    label: 'Dresses',
    value: 'dresses',
  },
  {
    id: 'cat-106',
    parent_id: 'cat-101',
    label: 'Tops',
    value: 'tops',
  },
  {
    id: 'cat-107',
    parent_id: 'cat-101',
    label: 'Pants',
    value: 'pants',
  },
  {
    id: 'cat-108',
    parent_id: 'cat-101',
    label: 'Skirts',
    value: 'skirts',
  },
  {
    id: 'cat-109',
    parent_id: 'cat-102',
    label: 'Heels',
    value: 'heels',
  },
  {
    id: 'cat-110',
    parent_id: 'cat-102',
    label: 'Flats',
    value: 'flats',
  },
  {
    id: 'cat-111',
    parent_id: 'cat-102',
    label: 'Sneakers',
    value: 'sneakers',
  },
  {
    id: 'cat-112',
    parent_id: 'cat-102',
    label: 'Boots',
    value: 'boots',
  },
  {
    id: 'cat-113',
    parent_id: 'cat-103',
    label: 'Jewelry',
    value: 'jewelry',
  },
  {
    id: 'cat-114',
    parent_id: 'cat-103',
    label: 'Watches',
    value: 'watches',
  },
  {
    id: 'cat-115',
    parent_id: 'cat-103',
    label: 'Sunglasses',
    value: 'sunglasses',
  },
  {
    id: 'cat-116',
    parent_id: 'cat-104',
    label: 'Handbags',
    value: 'handbags',
  },
  {
    id: 'cat-117',
    parent_id: 'cat-104',
    label: 'Tote Bags',
    value: 'tote-bags',
  },
  {
    id: 'cat-118',
    parent_id: 'cat-104',
    label: 'Backpacks',
    value: 'backpacks',
  },
  {
    id: 'cat-119',
    parent_id: 'cat-104',
    label: 'Clutches',
    value: 'clutches',
  },
  {
    id: 'cat-200',
    label: 'Kids and Baby Fashion',
    value: 'kids-and-baby-fashion',
  },
  {
    id: 'cat-201',
    parent_id: 'cat-200',
    label: 'Clothing',
    value: 'clothing',
  },
  {
    id: 'cat-202',
    parent_id: 'cat-200',
    label: 'Footwear',
    value: 'footwear',
  },
  {
    id: 'cat-203',
    parent_id: 'cat-200',
    label: 'Accessories',
    value: 'accessories',
  },
  {
    id: 'cat-204',
    parent_id: 'cat-200',
    label: 'Baby Gear',
    value: 'baby-gear',
  },
  {
    id: 'cat-205',
    parent_id: 'cat-201',
    label: 'T-Shirts',
    value: 't-shirts',
  },
  {
    id: 'cat-206',
    parent_id: 'cat-201',
    label: 'Dresses',
    value: 'dresses',
  },
  {
    id: 'cat-207',
    parent_id: 'cat-201',
    label: 'Pants & Shorts',
    value: 'pants-shorts',
  },
  {
    id: 'cat-208',
    parent_id: 'cat-201',
    label: 'Outerwear',
    value: 'outerwear',
  },
  {
    id: 'cat-209',
    parent_id: 'cat-202',
    label: 'Sneakers',
    value: 'sneakers',
  },
  {
    id: 'cat-210',
    parent_id: 'cat-202',
    label: 'Sandals',
    value: 'sandals',
  },
  {
    id: 'cat-211',
    parent_id: 'cat-202',
    label: 'Boots',
    value: 'boots',
  },
  {
    id: 'cat-212',
    parent_id: 'cat-202',
    label: 'Baby Shoes',
    value: 'baby-shoes',
  },
  {
    id: 'cat-213',
    parent_id: 'cat-203',
    label: 'Hats',
    value: 'hats',
  },
  {
    id: 'cat-214',
    parent_id: 'cat-203',
    label: 'Belts',
    value: 'belts',
  },
  {
    id: 'cat-215',
    parent_id: 'cat-203',
    label: 'Socks & Tights',
    value: 'socks-tights',
  },
  {
    id: 'cat-216',
    parent_id: 'cat-204',
    label: 'Diaper Bags',
    value: 'diaper-bags',
  },
  {
    id: 'cat-217',
    parent_id: 'cat-204',
    label: 'Baby Carriers',
    value: 'baby-carriers',
  },
  {
    id: 'cat-218',
    parent_id: 'cat-204',
    label: 'Strollers',
    value: 'strollers',
  },
  {
    id: 'cat-219',
    parent_id: 'cat-204',
    label: 'Blankets',
    value: 'blankets',
  },
  {
    id: 'cat-300',
    label: 'Books',
    value: 'books',
  },
  {
    id: 'cat-301',
    parent_id: 'cat-300',
    label: 'Fiction',
    value: 'fiction',
  },
  {
    id: 'cat-302',
    parent_id: 'cat-300',
    label: 'Non-Fiction',
    value: 'non-fiction',
  },
  {
    id: 'cat-303',
    parent_id: 'cat-300',
    label: "Children's Books",
    value: 'childrens-books',
  },
  {
    id: 'cat-304',
    parent_id: 'cat-300',
    label: 'Educational',
    value: 'educational',
  },
  {
    id: 'cat-305',
    parent_id: 'cat-301',
    label: 'Fantasy',
    value: 'fantasy',
  },
  {
    id: 'cat-306',
    parent_id: 'cat-301',
    label: 'Mystery',
    value: 'mystery',
  },
  {
    id: 'cat-307',
    parent_id: 'cat-301',
    label: 'Romance',
    value: 'romance',
  },
  {
    id: 'cat-308',
    parent_id: 'cat-301',
    label: 'Science Fiction',
    value: 'science-fiction',
  },
  {
    id: 'cat-309',
    parent_id: 'cat-302',
    label: 'Biographies',
    value: 'biographies',
  },
  {
    id: 'cat-310',
    parent_id: 'cat-302',
    label: 'Self-Help',
    value: 'self-help',
  },
  {
    id: 'cat-311',
    parent_id: 'cat-302',
    label: 'Cookbooks',
    value: 'cookbooks',
  },
  {
    id: 'cat-312',
    parent_id: 'cat-302',
    label: 'Travel',
    value: 'travel',
  },
  {
    id: 'cat-313',
    parent_id: 'cat-303',
    label: 'Picture Books',
    value: 'picture-books',
  },
  {
    id: 'cat-314',
    parent_id: 'cat-303',
    label: 'Early Readers',
    value: 'early-readers',
  },
  {
    id: 'cat-315',
    parent_id: 'cat-303',
    label: 'Young Adult',
    value: 'young-adult',
  },
  {
    id: 'cat-316',
    parent_id: 'cat-304',
    label: 'Textbooks',
    value: 'textbooks',
  },
  {
    id: 'cat-317',
    parent_id: 'cat-304',
    label: 'Reference',
    value: 'reference',
  },
  {
    id: 'cat-318',
    parent_id: 'cat-304',
    label: 'Test Prep',
    value: 'test-prep',
  },
  {
    id: 'cat-319',
    parent_id: 'cat-304',
    label: 'Language Learning',
    value: 'language-learning',
  },
  {
    id: 'cat-400',
    label: 'Muslim Fashion',
    value: 'muslim-fashion',
  },
  {
    id: 'cat-401',
    parent_id: 'cat-400',
    label: "Men's Wear",
    value: 'mens-wear',
  },
  {
    id: 'cat-402',
    parent_id: 'cat-400',
    label: "Women's Wear",
    value: 'womens-wear',
  },
  {
    id: 'cat-403',
    parent_id: 'cat-400',
    label: "Kids' Wear",
    value: 'kids-wear',
  },
  {
    id: 'cat-404',
    parent_id: 'cat-400',
    label: 'Accessories',
    value: 'accessories',
  },
  {
    id: 'cat-405',
    parent_id: 'cat-401',
    label: 'Koko Shirts',
    value: 'koko-shirts',
  },
  {
    id: 'cat-406',
    parent_id: 'cat-401',
    label: 'Sarongs',
    value: 'sarongs',
  },
  {
    id: 'cat-407',
    parent_id: 'cat-401',
    label: 'Prayer Outfits',
    value: 'prayer-outfits',
  },
  {
    id: 'cat-408',
    parent_id: 'cat-402',
    label: 'Hijabs',
    value: 'hijabs',
  },
  {
    id: 'cat-409',
    parent_id: 'cat-402',
    label: 'Abayas',
    value: 'abayas',
  },
  {
    id: 'cat-410',
    parent_id: 'cat-402',
    label: 'Kaftans',
    value: 'kaftans',
  },
  {
    id: 'cat-411',
    parent_id: 'cat-402',
    label: 'Prayer Outfits',
    value: 'prayer-outfits',
  },
  {
    id: 'cat-412',
    parent_id: 'cat-403',
    label: 'Koko Shirts for Kids',
    value: 'koko-shirts-for-kids',
  },
  {
    id: 'cat-413',
    parent_id: 'cat-403',
    label: 'Hijabs for Kids',
    value: 'hijabs-for-kids',
  },
  {
    id: 'cat-414',
    parent_id: 'cat-403',
    label: 'Prayer Outfits for Kids',
    value: 'prayer-outfits-for-kids',
  },
  {
    id: 'cat-415',
    parent_id: 'cat-404',
    label: 'Caps',
    value: 'caps',
  },
  {
    id: 'cat-416',
    parent_id: 'cat-404',
    label: 'Scarves',
    value: 'scarves',
  },
  {
    id: 'cat-417',
    parent_id: 'cat-404',
    label: 'Pins & Brooches',
    value: 'pins-brooches',
  },
  {
    id: 'cat-418',
    parent_id: 'cat-404',
    label: 'Tasbih',
    value: 'tasbih',
  },
  {
    id: 'cat-500',
    label: 'Audio, Camera and Other Electronics',
    value: 'audio-camera-and-other-electronics',
  },
  {
    id: 'cat-501',
    parent_id: 'cat-500',
    label: 'Audio',
    value: 'audio',
  },
  {
    id: 'cat-502',
    parent_id: 'cat-500',
    label: 'Cameras',
    value: 'cameras',
  },
  {
    id: 'cat-503',
    parent_id: 'cat-500',
    label: 'Gaming',
    value: 'gaming',
  },
  {
    id: 'cat-504',
    parent_id: 'cat-500',
    label: 'Wearable Electronics',
    value: 'wearable-electronics',
  },
  {
    id: 'cat-505',
    parent_id: 'cat-501',
    label: 'Headphones',
    value: 'headphones',
  },
  {
    id: 'cat-506',
    parent_id: 'cat-501',
    label: 'Speakers',
    value: 'speakers',
  },
  {
    id: 'cat-507',
    parent_id: 'cat-501',
    label: 'Soundbars',
    value: 'soundbars',
  },
  {
    id: 'cat-508',
    parent_id: 'cat-502',
    label: 'DSLR Cameras',
    value: 'dslr-cameras',
  },
  {
    id: 'cat-509',
    parent_id: 'cat-502',
    label: 'Mirrorless Cameras',
    value: 'mirrorless-cameras',
  },
  {
    id: 'cat-510',
    parent_id: 'cat-502',
    label: 'Action Cameras',
    value: 'action-cameras',
  },
  {
    id: 'cat-511',
    parent_id: 'cat-502',
    label: 'Camera Accessories',
    value: 'camera-accessories',
  },
  {
    id: 'cat-512',
    parent_id: 'cat-503',
    label: 'Gaming Consoles',
    value: 'gaming-consoles',
  },
  {
    id: 'cat-513',
    parent_id: 'cat-503',
    label: 'Gaming Accessories',
    value: 'gaming-accessories',
  },
  {
    id: 'cat-514',
    parent_id: 'cat-503',
    label: 'VR Headsets',
    value: 'vr-headsets',
  },
  {
    id: 'cat-515',
    parent_id: 'cat-504',
    label: 'Smartwatches',
    value: 'smartwatches',
  },
  {
    id: 'cat-516',
    parent_id: 'cat-504',
    label: 'Fitness Trackers',
    value: 'fitness-trackers',
  },
  {
    id: 'cat-517',
    parent_id: 'cat-504',
    label: 'Smart Glasses',
    value: 'smart-glasses',
  },
  {
    id: 'cat-600',
    label: 'Handphone, Tablet and Other Gadgets',
    value: 'handphone-tablet-and-other-gadgets',
  },
  {
    id: 'cat-601',
    parent_id: 'cat-600',
    label: 'Handphones',
    value: 'handphones',
  },
  {
    id: 'cat-602',
    parent_id: 'cat-600',
    label: 'Tablets',
    value: 'tablets',
  },
  {
    id: 'cat-603',
    parent_id: 'cat-600',
    label: 'Smart Gadgets',
    value: 'smart-gadgets',
  },
  {
    id: 'cat-604',
    parent_id: 'cat-600',
    label: 'Accessories',
    value: 'accessories',
  },
  {
    id: 'cat-605',
    parent_id: 'cat-601',
    label: 'Smartphones',
    value: 'smartphones',
  },
  {
    id: 'cat-606',
    parent_id: 'cat-601',
    label: 'Feature Phones',
    value: 'feature-phones',
  },
  {
    id: 'cat-607',
    parent_id: 'cat-601',
    label: 'Refurbished Phones',
    value: 'refurbished-phones',
  },
  {
    id: 'cat-608',
    parent_id: 'cat-602',
    label: 'Android Tablets',
    value: 'android-tablets',
  },
  {
    id: 'cat-609',
    parent_id: 'cat-602',
    label: 'iPads',
    value: 'ipads',
  },
  {
    id: 'cat-610',
    parent_id: 'cat-602',
    label: 'E-Readers',
    value: 'e-readers',
  },
  {
    id: 'cat-611',
    parent_id: 'cat-603',
    label: 'Smartwatches',
    value: 'smartwatches',
  },
  {
    id: 'cat-612',
    parent_id: 'cat-603',
    label: 'Fitness Trackers',
    value: 'fitness-trackers',
  },
  {
    id: 'cat-613',
    parent_id: 'cat-603',
    label: 'VR Headsets',
    value: 'vr-headsets',
  },
  {
    id: 'cat-614',
    parent_id: 'cat-604',
    label: 'Chargers',
    value: 'chargers',
  },
  {
    id: 'cat-615',
    parent_id: 'cat-604',
    label: 'Cases and Covers',
    value: 'cases-and-covers',
  },
  {
    id: 'cat-616',
    parent_id: 'cat-604',
    label: 'Power Banks',
    value: 'power-banks',
  },
  {
    id: 'cat-617',
    parent_id: 'cat-604',
    label: 'Headphones and Earbuds',
    value: 'headphones-and-earbuds',
  },
];
