export const categories = [
  {
    id: 'cat-1',
    label: 'Man Fashion',
    value: 'man-fashion',
  },
  {
    id: 'cat-2',
    parent_id: 'cat-1',
    label: 'Man Outer',
    value: 'man-outer',
  },
  {
    id: 'cat-3',
    parent_id: 'cat-1',
    label: 'Man Accesories',
    value: 'man-accesories',
  },
  {
    id: 'cat-4',
    parent_id: 'cat-1',
    label: 'Man Pants',
    value: 'man-pants',
  },
  {
    id: 'cat-5',
    parent_id: 'cat-1',
    label: 'Man Shoes',
    value: 'man-shoes',
  },
  {
    id: 'cat-7',
    parent_id: 'cat-2',
    label: 'Bomber Jacket',
    value: 'bomber-jaket',
  },
  {
    id: 'cat-8',
    parent_id: 'cat-2',
    label: 'Parka Jaket',
    value: 'parka-jacket',
  },
  {
    id: 'cat-9',
    parent_id: 'cat-2',
    label: 'Denim Jacket',
    value: 'denim-jacket',
  },
  {
    id: 'cat-10',
    parent_id: 'cat-2',
    label: 'Windbreaker Jacket',
    value: 'winbreaker-jacket',
  },
  {
    id: 'cat-11',
    parent_id: 'cat-2',
    label: 'Puffer Jacket',
    value: 'puffer-jacket',
  },
  {
    id: 'cat-12',
    parent_id: 'cat-3',
    label: 'Man Watches',
    value: 'man-watches',
  },
  {
    id: 'cat-13',
    parent_id: 'cat-3',
    label: 'Man Glasses',
    value: 'man-glasses',
  },
  {
    id: 'cat-14',
    parent_id: 'cat-3',
    label: 'Man Hats',
    value: 'man-hats',
  },
  {
    id: 'cat-15',
    parent_id: 'cat-3',
    label: 'Man Bags',
    value: 'man-bags',
  },
  {
    id: 'cat-16',
    parent_id: 'cat-3',
    label: 'Man Belts',
    value: 'man-belts',
  },
  {
    id: 'cat-17',
    parent_id: 'cat-4',
    label: 'Man Jeans',
    value: 'man-jeans',
  },
  {
    id: 'cat-18',
    parent_id: 'cat-4',
    label: 'Man Chinos',
    value: 'man-chinos',
  },
  {
    id: 'cat-19',
    parent_id: 'cat-4',
    label: 'Man Cargos',
    value: 'man-cargo',
  },
  {
    id: 'cat-20',
    parent_id: 'cat-4',
    label: 'Man Joggers',
    value: 'man-jogger',
  },
  {
    id: 'cat-21',
    parent_id: 'cat-4',
    label: 'Man Shorts',
    value: 'man-shorts',
  },
  {
    id: 'cat-22',
    parent_id: 'cat-5',
    label: 'Man Formals',
    value: 'man-formals',
  },
  {
    id: 'cat-23',
    parent_id: 'cat-5',
    label: 'Man Oxfords',
    value: 'man-oxfords',
  },
  {
    id: 'cat-24',
    parent_id: 'cat-5',
    label: 'Man Derbys',
    value: 'man-derbys',
  },
  {
    id: 'cat-25',
    parent_id: 'cat-5',
    label: 'Man Loafers',
    value: 'man-loafers',
  },
  {
    id: 'cat-26',
    parent_id: 'cat-5',
    label: 'Man Sneakers',
    value: 'man-sneakers',
  },
];
