import dotenv from 'dotenv';
dotenv.config();

export const CONFIGS = {
  PORT: process.env.PORT,
  SALT_ROUND: process.env.SALT_ROUND,
  JWT_SECRET: process.env.JWT_SECRET,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  BITESHIP_API_KEY: process.env.BITESHIP_API_KEY,
  MIDTRANS_SERVER_KEY: process.env.MIDTRANS_SERVER_KEY,
  MIDTRANS_CLIENT_KEY: process.env.MIDTRANS_CLIENT_KEY,
  TWILIO_ACCOUNT_SID: process.env.ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.AUTH_TOKEN,
  TWILIO_WHATSAPP_NUMBER: process.env.PHONE_NUMBER,
};
